import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F7F9',
    alignItems: 'center',
  },
  title: {
    fontFamily: 'Inter-Bold',
    fontSize: 64,
    color: '#243443',
  },
  profileButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    marginTop: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7F7F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  profilePhoto: {
    width: 54,
    height: 54,
    borderRadius: 27,
  },
  noChatFoundContainer: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
  },
  noChatFoundText: {
    fontFamily: 'Inter-Bold',
    fontSize: 24,
    color: '#243443',
    marginTop: 128,
  },
  findUsersHereText: {
    fontFamily: 'Inter-Bold',
    fontSize: 20,
    color: '#243443',
    position: 'absolute',
    bottom: 104,
    marginHorizontal: 'auto',
  },
  findUserHereImage: {
    width: 32,
    height: 32,
    position: 'absolute',
    bottom: 64,
    right: 124,
  },
  chatList: {
    flex: 1,
    width: '100%',
    padding: 16,
  },
  chatItemContainer: {
    width: '100%',
    paddingHorizontal: 28,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  chatItemPhoto: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  chatItemNameLastMessageContainer: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'space-between',
  },
  chatItemName: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 16,
    color: '#243443',
  },
  chatItemLastMessage: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    color: '#58616A',
  },
  chatItemIcon: {
    width: 24,
    height: 24,
  },
  searchUserButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    backgroundColor: '#377DFF',
    position: 'absolute',
    bottom: 32,
    right: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchUserIcon: {
    width: 40,
    height: 40,
  },
});
